### PR TITLE
automatic download of textures

### PR DESCRIPTION
**Pull request by JensMunkHansen**
Hi Melchor

Nice small compact repository. Great learning experience for signed distance fields. I did a small change, which automatically downloads textures in a cross-platform manner.

Up to you, if you like it.

### CODE REVIEW

**Comment by JensMunkHansen** [comment]
We should add this to make clean work properly.

set_target_properties(textures
  PROPERTIES
  ADDITIONAL_CLEAN_FILES ${CMAKE_CURRENT_BINARY_DIR}/res/textures
)

**Comment by melchor629** [comment]
Hi Jens. Thanks for the Pull Request! Really happy to see you liked my project :)

I've given a try and there are some suggestions I would like you to do before merging these changes.

**Comment by JensMunkHansen** [comment]
Okay, no problem. Locally, I removed all 3rd-party dependencies and rely on my installed versions of these (less space), but I guess it is better to leave that part as is. Let me know if you want me to do some changes.

**Comment by melchor629** [comment]
> Okay, no problem. Locally, I removed all 3rd-party dependencies and rely on my installed versions of these (less space), but I guess it is better to leave that part as is. Let me know if you want me to do some changes.

Dependencies are fine for now. I want to change from submodules to cmake directly, to be able to use local installed dependencies instead of those copies (if found in the machine). But I would rather do it in another change, and keep this PR just for the textures.

When possible, try my suggestions. If they work fine for you, then I will merge the changes.

**Comment by JensMunkHansen** [comment]
Perhaps, I am a noob. The suggestions that you mention, how do I get to see them.

**Comment by melchor629** [comment]
Ah don't worry :)

Below my first comment, in the page, you can see them.
screenshot-1

You can also go to the *Files Changed* in this PR to look at them better (they look similar to above screenshot, but in code).
screenshot-2

**Comment by JensMunkHansen** [comment]
I will change that to support Visual Studio :)

**Comment by JensMunkHansen** [comment]
I just tried it used Visual Studio on Windows 11 and CMake 3.24.2. It works flawlessly. Up to you, if you want to change anything. Soon, I will merge my feature branch into my fork, where I have removed all 3rd-party dependencies (which on Windows will require the user to manually install or build them elsewhere).

**Comment by JensMunkHansen** [comment]
I know what you are after. I decided to add a rename, so I didn't have to change the source from `textures` to `pics`. Using standard `CMAKE` unzip, it is not yet possible to junk the directories, `unzip -j`. If you want you can change the source code replace `textures` with `pics` and avoid the rename

**Comment by JensMunkHansen** [comment]
I have changed the source code to read from `BUILD_DIR/pics`. The folder that the textures gets extracted to

**Comment by jensmunkhansen3shape** [comment]
Now, you can rebuild like crazy without a clean.

**Comment by melchor629** [comment]
> I have changed the source code to read from `BUILD_DIR/pics`. The folder that the textures gets extracted to

I would prefer not to do any changes on the source, rather just download the images somewhere and copy them in the step that copies the resources to the output folder. On Linux, the folder is always in the same place, on Visual Studio (Windows) depends on a setting in the build, so it could change between builds. In fact, your initial changes did not work on VS because the files were outside the folder of where the binaries and resources are written. And as I said before, this folder depends on a setting in VS... 

That's where my suggestions go to. Download files to somewhere else, and then copy them in the same step I already have to copy resources to the output folder (compatible with Visual Studio). All these changes should only be in the build scripts, not in code.

**Comment by jensmunkhansen3shape** [comment]
It worked fine for me with the VS, just needed to set the start-up directory for the application to be the build directory and not some directory depending on the settings. Sometimes people introduce a run script for handling this.

If you do what you suggest, you will end up with multiple copies of the resources. I think that I will close this PR. I don't have access to a Windows machine - only through a cicd solution.

Sorry for inconvenience.

**Comment by melchor629** [comment]
Yeah, I know that there will be multiple copies. But they were already and that's fine I guess. For VS was already like this weird. I try to be as simple as possible without having to tweak many things on VS to be able to run and debug.

Anyway, if you don't mind, I would like to take your initial job and finish to have something better for textures. Didn't know that cmake had this tools available.
Also, as mentioned before, I would like to rework dependencies to avoid git submodules.

Thanks for the PR and don't worry, you did not cause any inconvenience :)

Have a nice day/evening/night.

**Pull request closed without merging**
